tap 'caskroom/cask'
tap 'homebrew/cask-fonts'
tap 'homebrew/cask-drivers'
tap 'azure/functions'

# Dev
brew 'azure-cli'
brew 'azure-functions-core-tools'
brew 'bat'
brew 'fish'
brew 'fzf'
brew 'git'
brew 'hub'
brew 'lastpass-cli'
brew 'n'
brew 'ripgrep'
brew 'yarn'

# Apps
cask 'anki'
cask 'alfred'
cask 'beyond-compare'
cask 'caprine'
cask 'discord'
cask 'docker'
cask 'firefox'
cask 'iterm2'
cask 'onedrive'
cask 'qmk-toolbox'
cask 'selfcontrol'
cask 'slack'
cask 'spotify'
cask 'visual-studio-code'

# Fonts
cask 'font-fira-code'