tap 'caskroom/cask'
tap 'homebrew/cask-fonts'
tap 'homebrew/cask-drivers'
tap 'lyft/formulae'
tap 'azure/functions'

# Dev
brew 'azure-cli'
brew 'azure-functions-core-tools'
brew 'fish'
brew 'git'
brew 'git-crypt'
brew 'imagemagick'
brew 'set-simulator-location'
brew 'n'
brew 'ripgrep'
brew 'yarn'

# Apps
cask 'beyond-compare'
cask 'caffeine'
cask 'caprine'
cask 'discord'
cask 'docker'
cask 'figma'
cask 'iterm2'
cask 'onedrive'
cask 'postman'
cask 'raycast'
cask 'slack'
cask 'spotify'
cask 'visual-studio-code'

# Fonts
cask 'font-fira-code'