abbr ga 'git add'
abbr gs 'git status'
abbr gb 'git branch'
abbr gcom 'git commit'
abbr gd 'git difftool --no-prompt'
abbr gdd 'git difftool --dir-diff'
abbr gco 'git checkout'
abbr gpr 'git pull --rebase'
abbr gr 'git rebase'
abbr rn 'react-native'
abbr mk 'minikube'